// React/goal_coach/src/components/SignUp.jsx
import React, { Component } from 'react';
import { Link } from 'react-router';
import { firebaseApp } from '../firebase';

class SignUp extends Component {
	constructor(props) {
		super(props);
		this.state = {
			email: '',
			password: '',
			error: {
				message: ''
			}
		}
	}

	signUp() {
		const { email, password } = this.state;
		firebaseApp.auth().createUserWithEmailAndPassword(email, password)
			.catch(error => {
				this.setState ({error})
			})
	}

	render() {
		return(
			<div className="form-inline">
				<h2>Sign Up</h2>
				
				<div className="form-group">
					<input
						className="form-control"
						type="text"
						placeholder="email"
						onChange={event => this.setState({email: event.target.value})}
					/>
					<input
						className="form-control"
						type="password"
						placeholder="password"
						onChange={event => this.setState({password: event.target.value})}
					/>
					<button 
						className="btn btn-primary"
						type="button"
						onClick={() => this.signUp()}
					>
						Sign Up
					</button>
				</div>
				<div>{this.state.error.message}</div>
				<div><Link to={'/signin'}>Already a user? Log in instead</Link></div>
			</div>
		)
	}
}

export default SignUp;

// VueJS/turnout/src/components/Signup.vue
<template>
	<div class="">
		<h3>Sign Up</h3>
		<div class="form-group">
			<input 
				type="text"
				placeholder="email"
				class="form-control"
				v-model="email"
			/>
			<input
				type="password"
				placeholder="password"
				class="form-control"
				v-model="password"
			/>
			<button class="btn btn-primary" @click="signUp">Sign Up</button>
		</div><br>
		<p>{{error.message}}</p><br>
		<router-link to="/signin">&nbsp;&nbsp;Already a user? Sign in!</router-link>
	</div>
</template>

<script>
	import {firebaseApp} from '../firebaseApp'

	export default {
		data() {
			return {
				email: '',
				password: '',
				error: {
					message: ''
				}
			}
		},
		methods: {
			signUp(){
				firebaseApp.auth().createUserWithEmailAndPassword(this.email, this.password)
				.catch(error => {
					this.error = error
				})
			}
		}
	}
</script>
