// React/goal_coach/src/components/SignIn.jsx
import React, { Component } from 'react';
import { Link } from 'react-router';
import { firebaseApp } from '../firebase';

class SignUp extends Component {
	constructor(props){
		super(props);
		this.state = {
			email: '',
			password: '',
			error: {
				message: ''
			}
		}
	}

	signIn() {
		const { email, password } = this.state;
		firebaseApp.auth().signInWithEmailAndPassword(email, password)
			.catch(error => {
				this.setState ({error})
			})
	}

	render() {
		return(
			<div className="form-inline">
				<h2>Sign In</h2>
				
				<div className="form-group">
					<input
						className="form-control"
						type="text"
						placeholder="email"
						onChange={event => this.setState({email: event.target.value})}
					/>
					<input
						className="form-control"
						type="password"
						placeholder="password"
						onChange={event => this.setState({password: event.target.value})}
					/>
					<button 
						className="btn btn-primary"
						type="button"
						onClick={() => this.signIn()}
					>
						Sign In
					</button>
				</div>
				<div>{this.state.error.message}</div>
				<div><Link to={'/signup'}>Create account</Link></div>
			</div>
		)
	}
}

export default SignUp;

// VueJS/turnout/src/components/Signin.vue
<template>
	<div class="form-inline">
		<h3>Sign In</h3>
		<div class="form-group">
			<input 
				type="text"
				placeholder="email"
				class="form-control"
				v-model="email"
			/>
			<input
				type="password"
				placeholder="password"
				class="form-control"
				v-model="password"
			/>
			<button class="btn btn-primary" @click="signIn">Sign In</button>
		</div><br>
		<p>{{error.message}}</p><br>
	</div>
</template>

<script>
	import {firebaseApp} from '../firebaseApp'

	export default {
		data() {
			return {
				email: '',
				password: '',
				error: {
					message: ''
				}
			}
		},
		methods: {
			signIn(){
				firebaseApp.auth().signInWithEmailAndPassword(this.email, this.password)
				.catch(error => {
					this.error = error
				})
			}
		}
	}
</script>
